# Creates a K8s Secret with the superuser credentials
apiVersion: v1
kind: Secret
metadata:
  name: ais-admin-secret
  namespace: ais
type: Opaque
stringData:
  SU-NAME: "${SU_NAME}"
  SU-PASS: "${SU_PASS}"