# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io

resources:
- certificate_metrics.yaml
- certificate_webhook.yaml
- issuer.yaml

configurations:
- kustomizeconfig.yaml
