#
# Contains list of mountpaths on hosts and their size.
# Make sure to adjust the mountpaths based on host setup.
# This variable is used by `ais_cleanup_all.yml`, `ais_cleanup_markers.yml` and,
# `ais_deploy_cluster.yml`.
#
# Mountpaths can also be passed as a command line variable i.e. using -e
# Eg.
# ANSIBLE_CONFIG=dev-test/ansible.cfg ansible-playbook -i dev-test/host.ini \
# ais_cleanup_all.yml  -e cluster=ais-1 -e ais_mpaths=["/ais/sda", "/ais/sdb",...,"/ais/sdj"] -e ais_mpath_size=9Ti
#

# ---
# ais_mpaths:
#   - "/ais/sda"
#   - "/ais/sdb"
#   - "/ais/sdc"
#   - "/ais/sdd"
#   - "/ais/sde"
#   - "/ais/sdf"
#   - "/ais/sdg"
#   - "/ais/sdh"
#   - "/ais/sdi"
#   - "/ais/sdj"
#
# ais_mpath_size: 9Ti
#
