apiVersion: apps/v1
kind: StatefulSet # TODO: this might not work with DGX deployment.
metadata:
  name: {{ template "ais.fullname" . }}-target
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    component: "{{ .Values.target.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.aiscluster.expected_target_nodes }}
  serviceName: {{ template "ais.fullname" . }}-target
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  {{ if .Values.aiscluster.target.externalVolumes }}
  volumeClaimTemplates:
    {{ range .Values.aiscluster.target.mountPaths }}
    - metadata:
        name: ais-pv-{{ . | replace "/" "-" }}
      spec:
        storageClassName: "ais"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.aiscluster.target.externalVolumesSize }}
    {{ end }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ template "ais.name" . }}
        component: "{{ .Values.target.name }}"
        release: {{ .Release.Name }}
        function: "storage"
    spec:
      initContainers:
        - name: populate-env
          image: {{ .Values.aiscluster.image.kubectl.repository }}:{{ .Values.aiscluster.image.kubectl.tag }}
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          env:
            - name: MY_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AIS_NODE_ROLE
              value: "target"
            - name: K8S_NS
              value: {{ .Release.Namespace }}
            - name: MY_SERVICE_TYPE
              value: {{ .Values.target.service.type }}
            - name: MY_SERVICE
              value: {{ template "ais.fullname" . }}-target
          command:
            - "/bin/bash"
          args: [ "-c", "/bin/bash /var/ais_config_template/set_initial_target_env.sh" ]
          volumeMounts:
            - name: config-template-mount
              mountPath: "/var/ais_config_template"
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: env-mount
              mountPath: "/var/ais_env"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.aiscluster.image.aisnode.repository }}:{{ .Values.aiscluster.image.aisnode.tag }}"
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          securityContext:
            # required for hostport to operate, or implement a full pod security policy
            privileged: true
            capabilities:
              add:
                {{ range .Values.aiscluster.k8s.container_capabilities }}
                - {{ . }}
                {{ end }}
          env:
            - name : AIS_CONF_FILE
              value : "/var/ais_config/ais.json"
            - name: AIS_LOCAL_CONF_FILE
              value: "/var/ais_config/ais_local.json"
            - name: STATSD_CONF_FILE
              value: "/var/statsd_config/statsd.json"
            - name: AIS_NODE_ROLE
              value: "target"
            - name: AIS_HELM_DEPLOYMENT
              value: "true"
            - name: AIS_PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{ if not .Values.aiscluster.skipHostIP }}
            - name: AIS_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{ end }}
            - name: AIS_HOST_PORT
              value: {{ .Values.aiscluster.target.hostPort | quote }}
            - name: AIS_NO_DISK_IO
              value: {{ .Values.target.config.nodiskio.enabled | quote }}
            - name: AIS_DRY_OBJ_SIZE
              value: {{ .Values.target.config.nodiskio.dryobjsize | quote }}
            - name: CLUSTERIP_PROXY_SERVICE_HOSTNAME
              value: {{ template "ais.fullname" . }}-proxy
            - name: CLUSTERIP_PROXY_SERVICE_PORT
              value: "{{ .Values.proxy.service.port }}"
          ports:
            - name: aistarget
              containerPort: {{ .Values.target.service.port }}
              {{ if and .Values.aiscluster.k8s.cluster_cidr .Values.aiscluster.target.hostPort }}
              hostPort: {{ .Values.aiscluster.target.hostPort }}
              {{ end }}
              protocol: TCP
          command: ["/bin/bash", "-c"]
          args: ["source /var/ais_env/env; /ais_docker_start.sh"]
          volumeMounts:
            - name: state-mount
              mountPath: "/etc/ais"
            - name: env-mount
              mountPath: /var/ais_env
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: statsd-config
              mountPath: "/var/statsd_config"
            {{ if ne .Values.aiscluster.awsSecretName "" }}
            - name: aws-creds
              mountPath: "/root/.aws"
            {{ end }}
            {{ if .Values.aiscluster.target.externalVolumes }}
            {{ range .Values.aiscluster.target.mountPaths }}
            - name: ais-pv-{{ . | replace "/" "-" }}
              mountPath: {{ . }}
              {{ end }}
            {{ else }}
              {{ range .Values.aiscluster.target.mountPaths }}
            - name: fspath{{ . | replace "/" "." }}
              mountPath: "{{ . }}"
              {{ end }}
            {{ end }}
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash", "-c", "/usr/bin/pkill -SIGINT aisnode" ]
          livenessProbe:
            httpGet:
              path: /v1/health
              port: {{ .Values.target.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health?readiness=true
              port: {{ .Values.target.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.target.resources | indent 12 }}
      securityContext:
        sysctls:
        {{ if .Values.aiscluster.k8s.sysctls.somaxconn }}
        - name: net.core.somaxconn
          value: {{ .Values.aiscluster.k8s.sysctls.somaxconn | quote }}
        {{ end }}
        - name: net.ipv4.ip_local_port_range
          value: "10240 65535"
      serviceAccount: {{ template "ais.name" . }}-sa
      nodeSelector:
         {{ .Values.target.nodeSelector.key }}: {{ template "ais.fullname" . }}
      volumes:
        - name: config-mount
          emptyDir: {}
        - name: config-template-mount
          configMap:
            name:  {{ template "ais.name" . }}-target
        {{ if ne .Values.aiscluster.awsSecretName "" }}
        - name: aws-creds
          secret:
            secretName: "{{ .Values.aiscluster.awsSecretName }}"
        {{ end }}
        - name: env-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/target"
        - name: state-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/target"
        - name: statsd-config
          configMap:
            name: {{ template "ais.name" . }}-statsd
        {{ if not .Values.aiscluster.target.externalVolumes }}
        {{ range .Values.aiscluster.target.mountPaths }}
        - name: fspath{{ . | replace "/" "-" }}
          hostPath:
            path: {{ . }}
        {{ end }}
        {{ end }}
    {{- with .Values.target.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        {{- range .Values.aiscluster.image.pullSecretNames }}
        - name: {{ . }}
        {{- end }}
