cluster: ais
# size:
protocol: http
imagePullSecrets:
# - name:
nodeImage:
  name: aistorage/aisnode
  tag: v3.31
initImage:
  name: aistorage/ais-init
  tag: v3.31
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.1
cloud:
  awsSecretName:
  gcpSecretName:
  ociSecretName:
configToUpdate:
shutdownCluster: false
cleanupData: false
cleanupMetadata: false
apiMode: 
clusterDomain:
stateStorageClass:
authNSecretName:
auth:
enableExternalLB: false
logsDir:
proxySpec:
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoExecute"
  hostPort: 51080
  servicePort: 51080
  portPublic: 51080
  portIntraControl: 51082
  portIntraData: 51083 

targetSpec:
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoExecute"
  hostPort: 51081
  servicePort: 51081
  portPublic: 51081
  portIntraControl: 51082
  portIntraData: 51083

proxyLB:
  enabled: false
  port: 51080
  annotations:
    prometheus.io/scrape: "true"