repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts

releases:
  - name: cloudnative-pg-operator
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    createNamespace: true
    wait: true