---
- hosts: "controller"
  gather_facts: no
  vars_files:
    - "vars/ais_mpaths.yml"
    - "vars/https_config.yml"
    - "vars/multihome.yml"
  vars:
    - k8s_namespace: "{{cluster}}"

  pre_tasks:
    - name: Validate if ais_mpaths is defined
      fail:
        msg: "Variable 'ais_mpaths' not found. Refer to https://github.com/NVIDIA/ais-k8s/tree/master/docs#aistore-cluster-creation-process and populate the var in 'ais_mpaths.yml'"
      when: ais_mpaths is undefined

    - name: Validate if ais_mpath_size is defined
      fail:
        msg: "Variable 'ais_mpath_size' not found. Refer to https://github.com/NVIDIA/ais-k8s/tree/master/docs#aistore-cluster-creation-process and populate the var in 'ais_mpaths.yml'"
      when: ais_mpath_size is undefined

    - name: Validate if cluster is defined
      fail:
        msg: "Variable 'cluster' not found. Add the 'cluster' variable during execution. Use: ansible-playbook -i hosts.ini ais_deploy_cluster.yml -e cluster=ais"
      when: cluster is undefined

  become: true
  roles:
    - create_namespace
    - create_pv
    - ais_deploy_cluster
