---
# Nodes to create PVs on -- other values will be pulled from the ais config
nodes:
  - computeinstance-e00axbkkkm3x7ny5sp
  - computeinstance-e00bz5nx9f2cbdyqbz
  - computeinstance-e00e89nm3ekwpm2zgv
  - computeinstance-e00fs4920nb2br5913
  - computeinstance-e00gzphk7zyhwntqx8
  - computeinstance-e00pwc84rde94pag5s
  - computeinstance-e00thzmqxjer73ecm7