certificate:
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - NVIDIA Corporation
    organizationalUnits:
      - NGC Storage
    countries:
      - US
  dnsNames:
    # used for readiness and liveness check
    - "localhost" 
    # used for registration of targets 
    - "ais-proxy"
    - "ais-target"
    # used for intra cluster communication
    - "*.ais-proxy.ais.svc.cluster.local"
    - "*.ais-target.ais.svc.cluster.local"
    # used for ais-operator communication
    - "ais-proxy.ais"
  ipAddresses:
    - 127.0.0.1
    - 10.8.54.22
    - 10.8.0.17
    - 10.8.54.3
    - 10.11.0.3
    - 10.11.0.2
    - 10.8.3.31
    - 10.11.59.11
    # LB
    - 10.10.177.173
    - 89.169.111.167
  emailAddress: ais@exchange.nvidia.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer