certificate:
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - NVIDIA Corporation
    organizationalUnits:
      - NGC Storage
    countries:
      - US
  dnsNames:
    # used for readiness and liveness check
    - "localhost" 
    # used for registration of targets 
    - "ais-proxy"
    - "ais-target"
    # consistent url for client pod
    - "ais-proxy.ais.svc.cluster.local"
    # used for intra cluster communication
    - "*.ais-proxy.ais.svc.cluster.local"
    - "*.ais-target.ais.svc.cluster.local"
    # used for ais-operator communication
    - "ais-proxy.ais"
    - "*.nsv.sjc4.nvmetal.net"
  ipAddresses:
    - 127.0.0.1
    - 10.150.56.227
    - 10.150.56.230
    - 10.150.56.225
  emailAddress: aistore@nvidia.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer