environments:
  default:
    values:
      - valuesPath: "./config/authn/default.yaml.gotmpl"
        https:
          valuesPath: "./config/authn/cert/default.yaml"
  tls:
    values:
      - valuesPath: "./config/authn/tls.yaml.gotmpl"
        https:
          valuesPath: "./config/authn/cert/tls.yaml"
  neb-fin: 
    values: 
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/nvidia.yaml.gotmpl?ref=main"
        https:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/neb-fin.yaml?ref=main"
    kubeContext: neb-fin
  oci-kratos:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/oci.yaml.gotmpl?ref=main"
        https:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/oci-kratos.yaml?ref=main"
    kubeContext: oci-kratos
  oci-ord:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/oci.yaml.gotmpl?ref=main"
        https:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/oci-ord.yaml?ref=main"
    kubeContext: oci-ord
  oci-iad:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/oci.yaml.gotmpl?ref=main"
        https:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/oci-iad.yaml?ref=main"
    kubeContext: oci-iad
  sjc4-dev:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/nvidia.yaml.gotmpl?ref=main"
        https:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/sjc4-dev.yaml?ref=main"
    kubeContext: sjc4-dev
---
releases:
  - name: ais-authn
    namespace: ais
    createNamespace: true
    chart: charts/authn
    version: 0.1.0
    values:
      - "./charts/authn/values.yaml.gotmpl"
      - "{{ .Environment.Values.valuesPath }}"
      - "{{ .Environment.Values.https.valuesPath }}"