apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../certmanager
- ../metrics

# Adds namespace to all resources.
namespace: ais-operator-system
# Should match the prefix of the namespace above
namePrefix: ais-operator-

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: controller-manager-metrics-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      create: true
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: metrics-certs
      version: v1
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: controller-manager-metrics-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      create: true
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: metrics-certs
      version: v1
- source:
    fieldPath: metadata.name
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      create: true
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      create: true
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
- source:
    fieldPath: metadata.namespace
    kind: Certificate
    name: serving-cert
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
    select:
      group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: ais-operator-validating-webhook-configuration
      version: v1
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
    select:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: aistores.ais.nvidia.com
      version: v1
- source:
    fieldPath: metadata.name
    kind: Certificate
    name: serving-cert
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
      index: 1
    select:
      group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: ais-operator-validating-webhook-configuration
      version: v1
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
      index: 1
    select:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: aistores.ais.nvidia.com
      version: v1

patches:
- path: manager_auth_metric_patch.yaml
- path: manager_webhook_patch.yaml
- path: webhook_cainjection_patch.yaml
- path: manager_env_patch.yaml
- path: manager_ca_configmap_patch.yaml
- path: manager_authn_ca_configmap_patch.yaml
- path: aistores_cainjection_patch.yaml
- path: aistores_keep_policy_patch.yaml

images:
- name: controller
  newName: aistorage/ais-operator
  newTag: v2.14.0
