apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ais-operator.fullname" . }}-metrics-certs
  labels:
  {{- include "ais-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "ais-operator.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "ais-operator.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "ais-operator.fullname" . }}-selfsigned-issuer'
  secretName: metrics-server-cert
