apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: aistore.nvidia.com
spec:
  sources:
    - secret:
        name: ca-root-secret
        key: tls.crt
  target:
    configMap:
      key: trust-bundle.pem
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: ais