image:
  repository: aistorage/ais-util
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ais-client

ais:
  endpoint: https://ais-proxy.ais.svc.cluster.local:51080

authn:
  enabled: true
  serviceURL: https://ais-authn.ais:52001
  secretName: ais-authn-su-creds

tls:
  insecureSkipVerify: false
  caConfigMap: aistore.nvidia.com
  bundleFile: trust-bundle.pem

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 2
    memory: 2Gi

nodeSelector: {}
tolerations: []
affinity: {}

podLabels: {}
podAnnotations: {}
