apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  carbon.conf: |
{{ .Files.Get "files/carbon.conf" | indent 4 }}
  storage-schemas.conf: |
{{ .Files.Get "files/storage-schemas.conf" | indent 4 }}

