# Default config for local KinD cluster
cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 5.8Ti
  # Apply shared label to run on one physical disk (for development/testing)
  mounts:
    - path: /ais/1
      label: shared
    - path: /ais/2
      label: shared
    - path: /ais/3
      label: shared
size: 3
protocol: https
tls:
  skipVerifyCert: false
  certificate:
    issuerRef:
      name: ca-issuer
      kind: ClusterIssuer
# "standard" is the default storageClass in KinD
stateStorageClass: standard
nodeImage:
  tag: v4.2
initImage:
  tag: v4.2
logSidecarImage:
  tag: v1.1
# See cloud-provider-kind or similar for LoadBalancer support
proxyLB:
  enabled: true
configToUpdate: {}
