cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 5.8Ti
  # Apply shared label to run on one physical disk (for development/testing)
  mounts:
    - path: /ais/1
      label: shared
    - path: /ais/2
      label: shared
    - path: /ais/3
      label: shared
size: 3
protocol: https
tls:
  skipVerifyCert: false
  secretName: "tls-certs"
nodeImage:
  tag: v4.2
initImage:
  tag: v4.2
logSidecarImage:
  tag: v1.1
configToUpdate:
  backend:
    aws: {}
  auth:
    enabled: true
    oidc:
      allowed_iss: [ "https://keycloak-server-service.keycloak.svc.cluster.local:8543/realms/aistore" ]

# Sets auth.oidc.issuer_ca_bundle above with an automatic mount-point for AIS to trust the issuer
issuerCAConfigMap: aistore.nvidia.com

# Used by the operator to fetch tokens for this specific cluster from the Keycloak Issuer
auth:
  serviceURL: "https://keycloak-server-service.keycloak.svc.cluster.local:8543/realms/aistore/protocol/openid-connect/token"
  usernamePassword:
    secretName: ais-admin-secret
    loginConf:
      clientID: "AIStore"
  tls:
    # Trust bundle is defined by authCAConfigmapName, mounted at default mountpath 
    insecureSkipVerify: false
stateStorageClass: "openebs-hostpath"
cleanupMetadata: true