cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 930Gi
  mounts:
    - path: /ais/vdc
    - path: /ais/vdd
    - path: /ais/vde
    - path: /ais/vdf
    - path: /ais/vdg
size: 3
protocol: http
https:
  skipVerifyCert: false
nodeImage:
  tag: v4.0-fuse
initImage:
  tag: v4.0
logSidecarImage:
  tag: v1.1
cloud:
  awsSecretName: "aws-creds"
configToUpdate:
  memsys:
    min_free: 8GiB
    to_gc: 8GiB
    hk_time: 3m
  backend:
    aws: {}
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
stateStorageClass: "local-path"
authNSecretName:
proxyLB:
  enabled: true