cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 13.2Ti
  mounts:
    - path: /ais/vdc
    - path: /ais/vdd
    - path: /ais/vde
    - path: /ais/vdf
    - path: /ais/vdg
    - path: /ais/vdh
    - path: /ais/vdi
size: 7
protocol: https
https:
  skipVerifyCert: false
  tlsSecret: "tls-certs"
imagePullSecrets:
  - name: regcred
nodeImage:
  tag: v4.0-fuse
initImage:
  tag: v4.0
logSidecarImage:
  tag: v1.1
cloud:
  awsSecretName: "aws-creds"
configToUpdate:
  memsys:
    min_free: 8GiB
    to_gc: 8GiB
    hk_time: 3m
  backend:
    aws: {}
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
stateStorageClass: "local-path"
authNSecretName: ais-authn-jwt-signing-key

auth: 
  serviceURL: https://ais-authn.ais:52001
  usernamePassword:
    secretName: ais-authn-su-creds
    secretNamespace: ais
  tls:
    insecureSkipVerify: true

proxyLB:
  enabled: true
targetSpec: 
  annotations: 
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
