cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 5.8Ti
  mounts:
    - path: "/ais/nvme0n1"
    - path: "/ais/nvme1n1"
    - path: "/ais/nvme2n1"
size: 3
protocol: https
https:
  skipVerifyCert: false
  tlsSecret: "tls-certs"
nodeImage:
  name: aistorage/aisnode
  tag: v4.0
initImage:
  name: aistorage/ais-init
  tag: v4.0
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.1
configToUpdate:
  memsys: 
    hk_time: 3m
  backend:
    aws: {}
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
stateStorageClass: "local-path"