apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ais-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sleep", "infinity" ]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: AIS_ENDPOINT
              value: {{ .Values.ais.endpoint | quote }}
            {{- if .Values.tls.insecureSkipVerify }}
            - name: AIS_SKIP_VERIFY_CRT
              value: "true"
            {{- end }}
            {{- if .Values.tls.caConfigMap }}
            - name: AIS_CLIENT_CA
              value: /etc/ais-ca/{{ .Values.tls.bundleFile }}
            {{- end }}
            {{- if .Values.authn.enabled }}
            - name: AIS_AUTHN_URL
              value: {{ .Values.authn.serviceURL | quote }}
            {{- if .Values.authn.secretName }}
            - name: AIS_AUTHN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authn.secretName }}
                  key: SU-NAME
            - name: AIS_AUTHN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authn.secretName }}
                  key: SU-PASS
            {{- end }}
            {{- end }}
          {{- if .Values.tls.caConfigMap }}
          volumeMounts:
            - name: ais-ca
              mountPath: /etc/ais-ca
              readOnly: true
          {{- end }}
      {{- if .Values.tls.caConfigMap }}
      volumes:
        - name: ais-ca
          configMap:
            name: {{ .Values.tls.caConfigMap }}
            optional: true
            items:
              - key: {{ .Values.tls.bundleFile }}
                path: {{ .Values.tls.bundleFile }}
      {{- end }}
